# Generated by Django 6.0.3 on 2026-07-23 10:57

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_booking_theater_emailtask_show_booking_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[movies.models.validate_youtube_url]),
        ),
    ]
