# Generated by Django 6.0.3 on 2026-09-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_stripeevent_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(db_index=True, max_length=20)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('CONVERTED', 'Converted to Booking'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], db_index=True, default='LOCKED', max_length=20)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_locks', to='movies.show')),
            ],
            options={
                'indexes': [models.Index(fields=['show', 'seat_number', 'status'], name='movies_seat_show_id_4bc98d_idx'), models.Index(fields=['expires_at', 'status'], name='movies_seat_expires_df143d_idx')],
            },
        ),
    ]
